### ISSUE TITLE
Custom csv ingestion code

### ISSUE THREAD

**Issue by fimmugit** [0xboz/zipline_bundle#2]
AS I am learning to use zipline for backtesting stocks, I came across your example which I think is simple to use. So I made some modifications to use in my stock csv data ingestion. This ingestion seems to finish with no warnings. However, when I test the example script buy_and_hold.py in zipline, it gives a keyerror like Equity(0  [AAPL]). It seems to me that the sid may not be ingested (correctly). 

I peek at the csvdir.py that comes with zipline, the writer writes the data differently than your way. With that script, I have no problem running my backtest. So the difference is within how writer writes data into the bundle?

Do you have any problem for your crypto backtests? Any idea to fix that?  I appreciate your help!

Best regards,

Sean

**Error trace:**
<details>
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\env_zipline\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\env_zipline\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\env_zipline\Scripts\zipline.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\zipline\__main__.py", line 107, in _
    return f(*args, **kwargs)
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\zipline\__main__.py", line 276, in run
    blotter=blotter,
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\zipline\utils\run_algo.py", line 229, in _run
    overwrite_sim_params=False,
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\zipline\algorithm.py", line 756, in run
    for perf in self.get_generator():
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\zipline\gens\tradesimulation.py", line 206, in transform
    for capital_change_packet in every_bar(dt):
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\zipline\gens\tradesimulation.py", line 120, in every_bar
    blotter.get_transactions(current_data)
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\zipline\finance\blotter\simulation_blotter.py", line 345, in get_transactions
    slippage.simulate(bar_data, asset, asset_orders):
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\zipline\finance\slippage.py", line 121, in simulate
    volume = data.current(asset, "volume")
  File "_protocol.pyx", line 121, in zipline._protocol.check_parameters.__call__.assert_keywords_and_call
  File "_protocol.pyx", line 332, in zipline._protocol.BarData.current
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\zipline\data\data_portal.py", line 524, in get_spot_value
    data_frequency,
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\zipline\data\data_portal.py", line 461, in _get_single_asset_value
    asset, field, session_label,
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\zipline\data\data_portal.py", line 748, in _get_daily_spot_value
    return reader.get_value(asset, dt, column)
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\zipline\data\dispatch_bar_reader.py", line 97, in get_value
    return r.get_value(asset, dt, field)
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\zipline\data\us_equity_pricing.py", line 742, in get_value
    ix = self.sid_day_index(sid, dt)
  File "c:\programdata\anaconda3\envs\env_zipline\lib\site-packages\zipline\data\us_equity_pricing.py", line 710, in sid_day_index
    offset = day_loc - self._calendar_offsets[sid]
KeyError: Equity(0 [AAPL])
</details>

**Below is my adapted code:**
<details>
import numpy as np
from trading_calendars import register_calendar_alias, get_calendar
import os
import sys
import pandas as pd
from logbook import Logger, StreamHandler
from . import core as bundles

handler = StreamHandler(sys.stdout, format_string=" | {record.message}")
logger = Logger(__name__)
logger.handlers.append(handler)

def exists(filename):
	try:
		f = open(filename)
		f.close()
		return True
	except IOError:
		return False

def get_symbols():
    stocks=pd.read_csv(custom_data_path + "/Stocks.txt", header=None)
    stks = stocks.iloc[:,0].tolist()
    return stks

@bundles.register("mycsv")
def csv_to_bundle(interval, extra, csvdir):

    csvdir = os.path.join(csvdir, extra)
    def ingest(environ,
               asset_db_writer,
               minute_bar_writer,
               daily_bar_writer,
               adjustment_writer,
               calendar,
               start_session,
               end_session,
               cache,
               show_progress,
               output_dir
               ):

        # Get all available csv filenames
        # test a couple symbols
        symbols = ['AAPL','MSFT']

        # Loop through the filenames and create a dict to keep some temp meta data
        ticker_pairs = [{
                         'symbol': s,
                         'interval':interval,
                         'file_path':csvdir+s+".txt",
                         'exchange': "NYSE"
                         }
                         for s in symbols if exists(csvdir+s+".txt") and os.path.getsize(csvdir+s+".txt") > 0]

        # Create an empty meta data dataframe
        metadata_dtype = [
            ('symbol', 'object'),
            ('asset_name', 'object'),
            ('start_date', 'datetime64[ns]'),
            ('end_date', 'datetime64[ns]'),
            ('first_traded', 'datetime64[ns]'),
            ('auto_close_date', 'datetime64[ns]'),
            ('exchange', 'object'), ]
        metadata = pd.DataFrame(
            np.empty(len(ticker_pairs), dtype=metadata_dtype))

        data_sets = []
        sessions = pd.DatetimeIndex(get_calendar('NYSE').sessions_in_range(start_session, end_session))

        for sid, ticker_pair in enumerate(ticker_pairs):
            logger.debug('%s: sid %s' % (ticker_pair['symbol'], sid))
            df = pd.read_csv(ticker_pair['file_path'],
                             index_col=0, header = None,
                             names = ('date', 'open', 'high', 'low', 'close', 'volume'),
                             parse_dates=['date'])

            df.index = df.index.tz_localize(tz='UTC')
            start_date = df.index[0]
            end_date = df.index[-1]

            # dealing with missing data
            if not df.index.equals(sessions):
                df = df.reindex(sessions, method='pad')

            # dealing with newly IPOs or stocks with short history
            if start_date > sessions[0]:
                df = df.loc[start_date:]
            symbol = ticker_pair['symbol']
            asset_name = ticker_pair['symbol']
            start_date = df.index[0]
            end_date = df.index[-1]
            first_traded = start_date
            auto_close_date = end_date + pd.Timedelta(days=1)
            exchange = ticker_pair['exchange']

            if interval == '1m':
                writer = minute_bar_writer
            else:
                writer = daily_bar_writer

            # Update metadata
            metadata.iloc[sid] = symbol, asset_name, start_date, end_date, first_traded, auto_close_date, exchange

            data_sets.append((sid, df))

        if data_sets != []:
            # Dealing with missing sessions in some data sets
            for data_set in data_sets:
                try:
                    writer.write(
                        [data_set], show_progress=True)
                except Exception as e:
                    print(e)

        asset_db_writer.write(equities=metadata)
        print(metadata)
        adjustment_writer.write()

    return ingest

register_calendar_alias("MY_CSV", "NYSE")

</details>

**Comment by fimmugit** [comment]
I figured it out. The (daily/minute_bar) writer accepts only a collection of (sid, DF) pairs. Therefore we CANNOT write each (sid, DF) pair one at a time as it is being produced. 

What should be done is:

`

        data_sets = []
        sessions = calendar.sessions_in_range(start_session, end_session)
        if interval == '1m':
            writer = minute_bar_writer
        else:
            writer = daily_bar_writer
        for sid, ticker_pair in enumerate(ticker_pairs):
            df = pd.read_csv(ticker_pair['file_path'],
                                index_col=0, header = None,
                                names = ('date', 'open', 'high', 'low', 'close', 'volume'),
                                parse_dates=['date'])

            symbol = ticker_pair['symbol']
            asset_name = ticker_pair['symbol']
            start_date = df.index[0]
            end_date = df.index[-1]
            first_traded = start_date
            auto_close_date = end_date + pd.Timedelta(days=1)
            exchange = ticker_pair['exchange']
            df = df.reindex(sessions.tz_localize(None))[start_date:end_date]
            df.fillna(method='ffill', inplace=True)

            # Update metadata
            metadata.iloc[sid] = symbol, asset_name, start_date, end_date, first_traded, auto_close_date, exchange
            data_sets.append((sid, df))
        writer.write(data_sets, show_progress=True)

`
